### ISSUE TITLE
C# file detection issue

### ISSUE THREAD

**Issue by vkidd** [obxyann/Sublime-Uncrustify#1]
Formatting C# files not working on **OSX Yosemite 10.10.4** w/ **Sublime Text Build 3083**. After installing Uncrustify, Sublime-Uncrustify, & setting up the config I consistently got an **"Unsupported Language: cs"** error when executing any of the Format commands.

I resolved the issue by changing the following on **line 211** in **Uncrustify.py**
_elif lang_name == "c#"_
to
_elif lang_name == "cs"_

**Comment by obxyann** [comment]
yes..it should be "cs" and 1.1.1 fixed, thx!
