### ISSUE TITLE
The "No selection!" dialog is annoying

### ISSUE THREAD

**Issue by mulle-nat** [obxyann/Sublime-Uncrustify#3]
I am pretty sure, no one else cares either. The easiest solution is to do nothing.

While I am at it, here is a convenient shortcut to "reindent" code with ctrl-i and this plugin:

`Sublime Text / Preferences ... / Key Bindings User`:

```
[
   { "keys": ["ctrl+i"], "command": "uncrustify_selection" },
]
```

**Comment by obxyann** [comment]
1.  The easiest solution is to do nothing. -> that's good idea
2.  Adding a shortcut key -> I had this plan in mind but never take a coding, I will add your suggest in next release.
