### ISSUE TITLE
selection formatting assumes indents relative to first selected line

### ISSUE THREAD

**Issue by ShafinKhadem** [obxyann/Sublime-Uncrustify#5]
@obxyann  @gdamore this plugin has a serious issue: it indents all lines relative to first selected line.
I have temporarily solved this issue modifying Uncrustify.py file a little. I have created a pull request. If you find it worth updating, please release an updated package.
Here is screenshot:
![peek 2017-10-14 17-26](https://user-images.githubusercontent.com/26321479/31575288-e1ce7180-b104-11e7-80d0-ad2f43f1d006.gif)

**Comment by obxyann** [comment]
@ShafinKhadem the codes you pasted inside this comment is hard to read, please 'folk' a git copy and send a 'pull requests' after modified or can you sent me a copy by email to obxyann @ gmail ?

**Comment by ShafinKhadem** [comment]
@obxyann I have created a pull request. Please check that.
